[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false

[client]
showErrorDetails = true

[theme]
primaryColor = "#1f2937"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f9fafb"
textColor = "#262730"

[global]
developmentMode = false

[logger]
level = "info" 